# Generated by Django 5.2.7 on 2025-10-14 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finance_manager_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('total_budget_managed', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reports_submitted', models.IntegerField(default=0)),
                ('team_size', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'finance_manager',
            },
        ),
        migrations.CreateModel(
            name='FinanceEmployee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finance_employee_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role_title', models.CharField(blank=True, max_length=100, null=True)),
                ('invoices_processed', models.IntegerField(default=0)),
                ('payments_verified', models.IntegerField(default=0)),
                ('total_amount_handled', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='finance.financemanager')),
            ],
            options={
                'db_table': 'finance_employee',
            },
        ),
    ]
