# Generated by Django 5.2.7 on 2026-07-23 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord'), ('Marketing', 'Marketing'), ('Property', 'Property'), ('Maintenance', 'Maintenance'), ('Reception', 'Reception'), ('Finance', 'Finance'), ('Collection', 'Collection'), ('Legal', 'Legal'), ('IT', 'IT'), ('General Manager', 'General Manager'), ('HR', 'HR'), ('Owner', 'Owner'), ('Check-In Check-Out', 'Check-In Check-Out')], max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('General Manager', 'General Manager'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Technician', 'Technician')], max_length=50, null=True)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
