# Generated by Django 5.2.7 on 2025-11-13 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Marketing Dept login', 'Marketing Dept login'), ('Property Management login', 'Property Management login'), ('Tenant Management Module', 'Tenant Management Module'), ('Maintenance Dept login', 'Maintenance Dept login'), ('Reception Dept login', 'Reception Dept login'), ('Finance Dept Login', 'Finance Dept Login'), ('Collection Dept login', 'Collection Dept login'), ('Legal Dept Login', 'Legal Dept Login'), ('IT Dept login', 'IT Dept login'), ('IT Technician', 'IT Technician'), ('Agreement Team', 'Agreement Team'), ('General Manager', 'General Manager'), ('Owner', 'Owner')], max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('General Manager', 'General Manager'), ('Manager', 'Manager'), ('Employee', 'Employee')], max_length=50, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
