# Generated by Django 5.2.7 on 2025-11-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord'), ('Marketing', 'Marketing'), ('Property', 'Property'), ('Maintenance', 'Maintenance'), ('Reception', 'Reception'), ('Finance', 'Finance'), ('Collection', 'Collection'), ('Legal', 'Legal'), ('IT', 'IT'), ('General Manager', 'General Manager'), ('HR', 'HR'), ('Owner', 'Owner')], max_length=100, null=True),
        ),
    ]
