# Generated by Django 5.2.7 on 2025-11-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('General Manager', 'General Manager'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Technician', 'Technician')], max_length=50, null=True),
        ),
    ]
