# Generated by Django 5.2.7 on 2025-12-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
    ]
