# Generated by Django 5.2.7 on 2026-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord'), ('Marketing', 'Marketing'), ('Property', 'Property'), ('Maintenance', 'Maintenance'), ('Reception', 'Reception'), ('Finance', 'Finance'), ('Collection', 'Collection'), ('Legal', 'Legal'), ('IT', 'IT'), ('General Manager', 'General Manager'), ('HR', 'HR'), ('Owner', 'Owner'), ('Check-In Check-Out', 'Check-In Check-Out')], max_length=100, null=True),
        ),
    ]
