# Generated by Django 5.2.7 on 2025-11-13 08:07

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='property_manager_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('properties_managed', models.IntegerField(default=0)),
                ('team_size', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'property_manager',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('building_details', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('flat_number', models.IntegerField(blank=True, null=True)),
                ('dimension_length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension_breadth_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rental_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=20)),
                ('hall', models.BooleanField(default=False)),
                ('bedroom_count', models.PositiveIntegerField(default=0)),
                ('kitchen', models.BooleanField(default=False)),
                ('attached_bathroom_count', models.PositiveIntegerField(default=0)),
                ('single_bathroom_count', models.PositiveIntegerField(default=0)),
                ('balcony', models.BooleanField(default=False)),
                ('store_room', models.BooleanField(default=False)),
                ('rental_for', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Family', 'Family'), ('Labour', 'Labour')], default='Family', max_length=20)),
                ('advance_amount_rent', models.IntegerField(blank=True, null=True)),
                ('expected_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreement_id', models.PositiveIntegerField(blank=True, null=True)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=5)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_assigned_to', to='authentication.user')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_created_by', to='authentication.user')),
            ],
            options={
                'db_table': 'property',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyEmployee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='property_employee_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_units', models.IntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='property.propertymanager')),
            ],
            options={
                'db_table': 'property_employee',
            },
        ),
    ]
