# Generated by Django 5.2.7 on 2026-01-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Commercial', 'Commercial'), ('Villa', 'Villa')], default='Residential', max_length=20),
        ),
    ]
