# Generated by Django 5.2.7 on 2026-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='builtup_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='carpet_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='google_map_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='year_of_construction',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
