# Generated by Django 5.2.7 on 2026-01-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_rental_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='attached_bathroom_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedroom_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='property',
            name='single_bathroom_count',
        ),
        migrations.RemoveField(
            model_name='property',
            name='store_room',
        ),
        migrations.RemoveField(
            model_name='property',
            name='videos',
        ),
    ]
