# Generated by Django 5.2.7 on 2026-08-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='property.building'),
        ),
    ]
