# Generated by Django 5.2.7 on 2026-08-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('property', '0005_backfill_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='assigned_to_new',
            field=models.ManyToManyField(blank=True, related_name='property_assigned_to', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='property',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_assigned_to_old', to='authentication.user'),
        ),
    ]
