# Generated by Django 5.2.7 on 2026-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_add_property_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyPhotos',
        ),
    ]
