# Generated by Django 5.2.7 on 2026-01-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_delete_propertyphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhotos',
            fields=[
                ('property_photos_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Property Photo Id')),
                ('photo', models.URLField(max_length=500, verbose_name='Property Photo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Photo',
                'verbose_name_plural': 'Property Photos',
                'db_table': 'property_photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
