# Generated by Django 5.2.7 on 2026-03-14 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_propertyphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProperty',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='property.property')),
                ('commercial_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'commercial_property',
            },
        ),
        migrations.AlterField(
            model_name='propertyphotos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/', verbose_name='Property Photo'),
        ),
    ]
