# Generated by Django 5.2.7 on 2026-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_commercialproperty_alter_propertyphotos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphotos',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='property_photos/', verbose_name='Property Photo'),
        ),
    ]
