# Generated by Django 5.2.7 on 2026-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_swap_assigned_to_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='allowed_tenant_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='building',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='building',
            name='rental_purpose',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='rental_purpose',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
