# Generated by Django 5.2.7 on 2026-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_propertyphotos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='electricity_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='water_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
