# Generated by Django 5.2.7 on 2026-08-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_building_allowed_tenant_types_building_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Commercial', 'Commercial'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse')], max_length=20, null=True),
        ),
    ]
