# Generated by Django 5.2.7 on 2026-03-31 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('lead', '0003_remove_lead_id_alter_lead_lead_id'),
        ('property', '0010_propertydetail_electricity_charge_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAssignment',
            fields=[
                ('property_assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('tenant_type', models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rental_start_date', models.DateField(blank=True, null=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('agreement_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('maintenance_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_rent_paid', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card')], max_length=20, null=True)),
                ('agreement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('agreement_status', models.CharField(choices=[('Pending', 'Pending'), ('Prepared', 'Prepared'), ('Signed', 'Signed'), ('Executed', 'Executed'), ('Terminated', 'Terminated')], default='Pending', max_length=20)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='property/agreements/')),
                ('key_available_in_office', models.BooleanField(default=False)),
                ('key_code', models.CharField(blank=True, max_length=100, null=True)),
                ('key_handover_date', models.DateField(blank=True, null=True)),
                ('key_handover_status', models.CharField(choices=[('Pending', 'Pending'), ('Handed Over', 'Handed Over'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('electricity_meter_number', models.CharField(blank=True, max_length=100, null=True)),
                ('electricity_meter_reading_start', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('water_meter_reading_start', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gas_meter_reading_start', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finance_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('On Hold', 'On Hold'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rent_entry_created', models.BooleanField(default=False)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('maintenance_required', models.BooleanField(default=False)),
                ('maintenance_ticket_id', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Required', 'Not Required')], default='Pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('tenant_special_requirements', models.TextField(blank=True, default='')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('unassigned_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agreement_prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_prepared', to='authentication.user')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_assignments_created', to='authentication.user')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='property.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_assignments', to='lead.lead')),
            ],
            options={
                'db_table': 'property_assignment',
                'ordering': ['-assigned_on'],
            },
        ),
    ]
