# Generated by Django 5.2.7 on 2026-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_backfill_building_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='allowed_industry_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='building',
            name='cctv',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='commercial_category',
            field=models.CharField(blank=True, choices=[('Shop', 'Shop'), ('Office', 'Office'), ('Showroom', 'Showroom'), ('Godown', 'Godown'), ('Industrial Unit', 'Industrial Unit')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='emergency_exit',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='fire_safety_compliant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='has_dg_backup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='has_drainage_system',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='has_internet_fiber',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='has_transformer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='industrial_estate_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='lift_type',
            field=models.CharField(blank=True, choices=[('Passenger', 'Passenger'), ('Goods', 'Goods'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('Owned', 'Owned'), ('Leased', 'Leased')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='parking_availability',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Covered', 'Covered'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='power_load_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='project_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='warehouse_category',
            field=models.CharField(blank=True, choices=[('Industrial Warehouse', 'Industrial Warehouse'), ('Logistics Warehouse', 'Logistics Warehouse'), ('Cold Storage', 'Cold Storage'), ('Godown', 'Godown')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='water_supply_source',
            field=models.CharField(blank=True, choices=[('Borewell', 'Borewell'), ('Municipal', 'Municipal'), ('Tanker', 'Tanker')], max_length=20, null=True),
        ),
    ]
