# Generated by Django 5.2.7 on 2026-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_propertyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyassignment',
            name='agreement_type',
            field=models.CharField(blank=True, choices=[('Government Agreement', 'Government Agreement'), ('Internal Agreement', 'Internal Agreement')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyassignment',
            name='invoice_generated',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyassignment',
            name='key_available_in_office',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyassignment',
            name='maintenance_required',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyassignment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyassignment',
            name='rent_entry_created',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
    ]
