# Generated by Django 5.2.7 on 2026-04-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_propertyassignment_agreement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='electricity_charge_type',
            field=models.CharField(blank=True, choices=[('Meter', 'Meter'), ('Fixed', 'Fixed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='late_fee_type',
            field=models.CharField(choices=[('Day wise', 'Day wise'), ('Month wise', 'Month wise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='water_charge_type',
            field=models.CharField(blank=True, choices=[('Meter', 'Meter'), ('Fixed', 'Fixed')], max_length=20, null=True),
        ),
    ]
