# Generated by Django 5.2.7 on 2026-08-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_building_allowed_industry_types_building_cctv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='boundary_wall',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='childrens_play_area',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='clubhouse_access',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='driveway',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='fire_safety',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gas_pipeline',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gated_community',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='intercom',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='internal_roads',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='lift',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='parking',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='power_backup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='private_garden',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='private_parking',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Covered', 'Covered'), ('Both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='security',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='security_guard',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='street_lights',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='swimming_pool',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Private', 'Private'), ('Common', 'Common')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='terrace_access',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='water_supply',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='water_supply_24x7',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
