# Generated by Django 5.2.7 on 2026-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_propertydetail_electricity_charge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='current_tenant',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
