# Generated by Django 5.2.7 on 2026-08-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_building_boundary_wall_building_childrens_play_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPhotos',
            fields=[
                ('building_photos_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Building Photo Id')),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='building_photos/', verbose_name='Building Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.building')),
            ],
            options={
                'verbose_name': 'Building Photo',
                'verbose_name_plural': 'Building Photos',
                'db_table': 'building_photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
