# Generated by Django 5.2.7 on 2026-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_buildingphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='commercial_category',
            field=models.CharField(blank=True, choices=[('Shop', 'Shop'), ('Office', 'Office'), ('Showroom', 'Showroom'), ('Godown', 'Godown'), ('Industrial Unit', 'Industrial Unit'), ('Residential / Commercial', 'Residential / Commercial')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='commercial_category',
            field=models.CharField(blank=True, choices=[('Shop', 'Shop'), ('Office', 'Office'), ('Showroom', 'Showroom'), ('Godown', 'Godown'), ('Industrial Unit', 'Industrial Unit'), ('Residential / Commercial', 'Residential / Commercial')], max_length=30, null=True),
        ),
    ]
