# Generated by Django 5.2.7 on 2026-05-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_propertydetail_current_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='allowed_industry_types',
            field=models.JSONField(blank=True, default=list, help_text="Example: ['FMCG', 'Pharma', 'E-commerce']", null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='cam_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='clear_height_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='column_spacing_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='container_access',
            field=models.CharField(blank=True, choices=[('20 ft', '20 ft'), ('40 ft', '40 ft'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='dock_height_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='entry_gate_width_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='floor_load_capacity_mt_sqft',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='has_drainage_system',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='has_internet_fiber',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='has_mezzanine_floor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='has_transformer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='has_weighbridge_nearby',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='industrial_estate_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='maintenance_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='monthly_rent_type',
            field=models.CharField(blank=True, choices=[('Per Sq. Ft.', 'Per Sq. Ft.'), ('Lump Sum', 'Lump Sum')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='no_of_bays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='no_of_loading_docks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='office_space_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('Owned', 'Owned'), ('Leased', 'Leased')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='pantry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='plot_shed_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='rent_escalation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='road_width_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='security_deposit_type',
            field=models.CharField(blank=True, choices=[('Months', 'Months'), ('Amount', 'Amount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='super_builtup_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='swimming_pool',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Private', 'Private'), ('Common', 'Common')], default='No', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='truck_parking_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='turning_radius',
            field=models.CharField(blank=True, choices=[('Adequate', 'Adequate'), ('Limited', 'Limited')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='warehouse_category',
            field=models.CharField(blank=True, choices=[('Industrial Warehouse', 'Industrial Warehouse'), ('Logistics Warehouse', 'Logistics Warehouse'), ('Cold Storage', 'Cold Storage'), ('Godown', 'Godown')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='water_supply_source',
            field=models.CharField(blank=True, choices=[('Borewell', 'Borewell'), ('Municipal', 'Municipal'), ('Tanker', 'Tanker')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Commercial', 'Commercial'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse')], default='Residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='security_deposit_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
