# Generated by Django 5.2.7 on 2026-06-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_propertydetail_allowed_industry_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('Unfurnished', 'Unfurnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Fully Furnished', 'Fully Furnished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='rent_increase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
