# Generated by Django 5.2.7 on 2026-09-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_building_commercial_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='lift_type',
            field=models.CharField(blank=True, choices=[('Passenger', 'Passenger'), ('Goods', 'Goods'), ('Both', 'Both'), ('No Lift', 'No Lift')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='parking_availability',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Covered', 'Covered'), ('Both', 'Both'), ('No Parking', 'No Parking')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='lift_type',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Goods', 'Goods'), ('Both', 'Both'), ('No Lift', 'No Lift')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='parking_availability',
            field=models.CharField(choices=[('Open', 'Open'), ('Covered', 'Covered'), ('Both', 'Both'), ('No Parking', 'No Parking')], max_length=20, null=True),
        ),
    ]
