# Generated by Django 5.2.7 on 2026-09-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_commercial_no_lift_no_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='allowed_business_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
