# Generated by Django 5.2.7 on 2026-09-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_commercial_allowed_business_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='loading_area',
            field=models.CharField(choices=[('Warehouse', 'Warehouse'), ('Godown', 'Godown'), ('Parking', 'Parking')], max_length=12, null=True),
        ),
    ]
