# Generated by Django 5.2.7 on 2026-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_loading_area_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='power_supply',
            field=models.CharField(blank=True, choices=[('Single-Phase', 'Single-Phase'), ('Three-Phase', 'Three-Phase')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='power_supply',
            field=models.CharField(blank=True, choices=[('Single-Phase', 'Single-Phase'), ('Three-Phase', 'Three-Phase')], max_length=20, null=True),
        ),
    ]
