# Generated by Django 5.2.7 on 2026-09-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_commercial_power_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Commercial', 'Commercial'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse'), ('Residential / Commercial', 'Residential / Commercial')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Commercial', 'Commercial'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse'), ('Residential / Commercial', 'Residential / Commercial')], default='Residential', max_length=25),
        ),
    ]
