# Generated by Django 5.2.7 on 2026-09-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_residential_commercial_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='number_of_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
