# Generated by Django 5.2.7 on 2026-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_building_number_of_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='allowed_industry_types_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='allowed_industry_types_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
