# Generated by Django 5.2.7 on 2025-11-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=15, verbose_name='Lastname')),
                ('lead_origin', models.CharField(choices=[('web user', 'Web User'), ('admin', 'Admin'), ('application', 'Application'), ('wa', 'WA'), ('marketing team', 'Marketing team')], max_length=20, verbose_name='Lead Origin')),
                ('address', models.TextField(verbose_name='Address')),
                ('passport_or_id', models.CharField(max_length=50, verbose_name='Passport/ID')),
                ('purpose', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=10, verbose_name='Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('lead_assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assign', to='authentication.user', verbose_name='Lead Assigned')),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.user', verbose_name='Lead User')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.country', verbose_name='Nationality')),
            ],
            options={
                'db_table': 'lead',
            },
        ),
    ]
