# Generated by Django 5.2.7 on 2026-01-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('common', '0001_initial'),
        ('helper_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=15, verbose_name='Lastname')),
                ('type_of_tenant', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Married', 'Married')], max_length=15, null=True, verbose_name='Type of Tenant')),
                ('feedback', models.TextField(null=True, verbose_name='Feedback')),
                ('lead_origin', models.CharField(choices=[('Open Sooq', 'Open Sooq'), ('OLX', 'OLX'), ('Employee Referral', 'Employee Referral'), ('Reference', 'Reference'), ('Website Inquiry', 'Website Inquiry'), ('Social Media', 'Social Media'), ('Walk-in Customer', 'Walk-in Customer'), ('Phone Call Inquiry', 'Phone Call Inquiry'), ('Office Visit', 'Office Visit'), ('Online Property Portal', 'Online Property Portal'), ('Printing- Banner, Flex, Hoardings', 'Printing- Banner, Flex, Hoardings')], max_length=50, verbose_name='Lead Origin')),
                ('address', models.TextField(verbose_name='Address')),
                ('passport_or_id', models.CharField(max_length=50, verbose_name='Passport/ID')),
                ('purpose', models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], max_length=10, verbose_name='Purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helper_apis.city', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helper_apis.country', verbose_name='Country')),
                ('lead_assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assign', to='authentication.user', verbose_name='Lead Assigned')),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.user', verbose_name='Lead User')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helper_apis.nationality', verbose_name='Nationality')),
                ('property_permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission')),
            ],
            options={
                'db_table': 'lead',
            },
        ),
    ]
