# Generated by Django 5.2.7 on 2026-07-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('common', '0001_initial'),
        ('helper_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='authentication.user', verbose_name='Lead User')),
                ('first_name', models.CharField(max_length=100, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Lastname')),
                ('lead_category', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Married', 'Married')], max_length=15, null=True, verbose_name='Lead Category')),
                ('feedback', models.TextField(null=True, verbose_name='Feedback')),
                ('lead_origin', models.CharField(choices=[('Open Sooq', 'Open Sooq'), ('OLX', 'OLX'), ('Employee Referral', 'Employee Referral'), ('Reference', 'Reference'), ('Website Inquiry', 'Website Inquiry'), ('Social Media', 'Social Media'), ('Walk-in Customer', 'Walk-in Customer'), ('Phone Call Inquiry', 'Phone Call Inquiry'), ('Office Visit', 'Office Visit'), ('Online Property Portal', 'Online Property Portal'), ('Printing- Banner, Flex, Hoardings', 'Printing- Banner, Flex, Hoardings')], max_length=50, verbose_name='Lead Origin')),
                ('address', models.TextField(verbose_name='Address')),
                ('po_box', models.CharField(max_length=20, verbose_name='PO Box')),
                ('profile_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='lead_profiles', verbose_name='Profile Image')),
                ('passport_or_id', models.CharField(max_length=50, verbose_name='Passport/ID')),
                ('civil_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Civil ID')),
                ('purpose', models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], max_length=10, verbose_name='Purpose')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tenant_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant_type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helper_apis.city', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helper_apis.country', verbose_name='Country')),
                ('lead_assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assign', to='authentication.user', verbose_name='Lead Assigned')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helper_apis.nationality', verbose_name='Nationality')),
                ('property_permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission')),
            ],
            options={
                'db_table': 'lead',
            },
        ),
    ]
