# Generated by Django 5.2.7 on 2026-01-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='po_box',
            field=models.CharField(default='hjkfls', max_length=20, verbose_name='PO Box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='lead_profiles', verbose_name='Profile Image'),
        ),
    ]
