# Generated by Django 5.2.7 on 2026-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_origin',
            field=models.CharField(blank=True, choices=[('Open Sooq', 'Open Sooq'), ('OLX', 'OLX'), ('Employee Referral', 'Employee Referral'), ('Reference', 'Reference'), ('Website Inquiry', 'Website Inquiry'), ('Social Media', 'Social Media'), ('Walk-in Customer', 'Walk-in Customer'), ('Phone Call Inquiry', 'Phone Call Inquiry'), ('Office Visit', 'Office Visit'), ('Online Property Portal', 'Online Property Portal'), ('Printing- Banner, Flex, Hoardings', 'Printing- Banner, Flex, Hoardings')], max_length=50, null=True, verbose_name='Lead Origin'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='passport_or_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport/ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='po_box',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PO Box'),
        ),
    ]
