# Generated by Django 5.2.7 on 2025-12-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_propertypermission'),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_origin',
            field=models.CharField(choices=[('Web User', 'Web User'), ('Admin', 'Admin'), ('Application', 'Application'), ('WA', 'WA'), ('Marketing Team', 'Marketing Team')], max_length=20, verbose_name='Lead Origin'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='purpose',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], max_length=10, verbose_name='Purpose'),
        ),
    ]
