# Generated by Django 5.2.7 on 2025-11-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Lead Permission Id')),
                ('property', models.BooleanField(default=False, verbose_name='Is Property Permitted')),
            ],
            options={
                'db_table': 'lead_permission',
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_origin',
            field=models.CharField(choices=[('Web User', 'Web User'), ('Admin', 'Admin'), ('Application', 'Application'), ('WA', 'WA'), ('Marketing Team', 'Marketing Team')], max_length=20, verbose_name='Lead Origin'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='purpose',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], max_length=10, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='lead',
            name='proprty_permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lead.propertypermission'),
            preserve_default=False,
        ),
    ]
