# Generated by Django 5.2.7 on 2025-11-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_propertypermission_alter_lead_lead_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='proprty_permissions',
        ),
        migrations.AddField(
            model_name='lead',
            name='property_permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lead.propertypermission'),
        ),
    ]
