# Generated by Django 5.2.7 on 2026-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_address_alter_lead_lead_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estimated_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
