# Generated by Django 5.2.7 on 2026-01-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('lead', '0002_lead_po_box_lead_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='id',
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='authentication.user', verbose_name='Lead User'),
        ),
    ]
