# Generated by Django 5.2.7 on 2026-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_remove_lead_id_alter_lead_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
