# Generated by Django 5.2.7 on 2026-04-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='type_of_tenant',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_category',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Married', 'Married')], max_length=15, null=True, verbose_name='Lead Category'),
        ),
    ]
