# Generated by Django 5.2.7 on 2026-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_remove_lead_type_of_tenant_lead_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='civil_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Civil ID'),
        ),
    ]
