# Generated by Django 5.2.7 on 2026-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_lead_civil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Lastname'),
        ),
    ]
