# Generated by Django 5.2.7 on 2026-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_lead_company_name_lead_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
