from dataclasses import dataclass
from typing import Optional


@dataclass
class BuildingUpdateRequest:
    building_id: int
    name: Optional[str] = None
    property_type: Optional[str] = None
    block: Optional[str] = None
    total_floors: Optional[int] = None
    year_of_construction: Optional[int] = None
    facilities: Optional[list] = None
    rental_purpose: Optional[str] = None
    allowed_tenant_types: Optional[list] = None
    parking: Optional[bool] = None
    lift: Optional[bool] = None
    security: Optional[bool] = None
    gas_pipeline: Optional[bool] = None
    water_supply: Optional[bool] = None
    intercom: Optional[bool] = None
    fire_safety: Optional[bool] = None
    project_name: Optional[str] = None
    private_garden: Optional[bool] = None
    private_parking: Optional[str] = None
    swimming_pool: Optional[str] = None
    terrace_access: Optional[bool] = None
    boundary_wall: Optional[bool] = None
    driveway: Optional[bool] = None
    water_supply_24x7: Optional[bool] = None
    security_guard: Optional[bool] = None
    clubhouse_access: Optional[bool] = None
    gym: Optional[bool] = None
    childrens_play_area: Optional[bool] = None
    internal_roads: Optional[bool] = None
    street_lights: Optional[bool] = None
    gated_community: Optional[bool] = None
    power_backup: Optional[bool] = None
    commercial_category: Optional[str] = None
    lift_type: Optional[str] = None
    fire_safety_compliant: Optional[bool] = None
    emergency_exit: Optional[bool] = None
    parking_availability: Optional[str] = None
    cctv: Optional[bool] = None
    warehouse_category: Optional[str] = None
    industrial_estate_name: Optional[str] = None
    ownership_type: Optional[str] = None
    has_transformer: Optional[bool] = None
    water_supply_source: Optional[str] = None
    has_drainage_system: Optional[bool] = None
    has_internet_fiber: Optional[bool] = None
    allowed_industry_types: Optional[list] = None
    power_load_kw: Optional[float] = None
    has_dg_backup: Optional[bool] = None
    address_line_1: Optional[str] = None
    address_line_2: Optional[str] = None
    area_zone: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    country: Optional[str] = None
    pincode: Optional[str] = None
    google_map_location: Optional[str] = None
    internal_notes: Optional[str] = None
    user_id: Optional[int] = None
