# Generated by Django 5.2.7 on 2026-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='assigned_to_employee_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='listed_for_rent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='property_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='property_occupied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='tenant_assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
