# Generated by Django 5.2.7 on 2026-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=20, null=True),
        ),
    ]
