# Generated by Django 5.2.7 on 2026-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0002_checkoutpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='charge_type',
            field=models.CharField(blank=True, choices=[('Security Deposit Refund', 'Security Deposit Refund'), ('Deduction', 'Deduction'), ('Pending Dues', 'Pending Dues'), ('Rent', 'Rent'), ('Maintenance', 'Maintenance'), ('Damage', 'Damage'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
