# Generated by Django 5.2.7 on 2026-07-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0003_alter_checkout_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutpayment',
            name='charge_type',
            field=models.CharField(blank=True, choices=[('Security Deposit Refund', 'Security Deposit Refund'), ('Deduction', 'Deduction'), ('Pending Dues', 'Pending Dues'), ('Rent', 'Rent'), ('Maintenance', 'Maintenance'), ('Damage', 'Damage'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
