# Generated by Django 5.2.7 on 2026-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0004_checkoutpayment_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='key_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
