# Generated by Django 5.2.7 on 2026-06-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('checkin_checkout', '0004_checkin_inspection_duration_checkin_inspection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_approved', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='inspector_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkin',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_recommended', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='checkininspectionitem',
            name='item_approval_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=20, null=True),
        ),
    ]
