# Generated by Django 5.2.7 on 2026-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0005_checkout_key_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdocument',
            name='document_type',
            field=models.CharField(choices=[('Tenant ID Proof', 'Tenant ID Proof'), ('Passport Copy', 'Passport Copy'), ('Address Proof', 'Address Proof'), ('Police Clearance', 'Police Clearance'), ('Agreement Copy', 'Agreement Copy'), ('Agreement Signed', 'Agreement Signed'), ('Company Seal', 'Company Seal'), ('Inspection Photo', 'Inspection Photo'), ('Meter Reading Photo', 'Meter Reading Photo'), ('Property Photo', 'Property Photo'), ('Key Return Photo', 'Key Return Photo'), ('Repair Document', 'Repair Document'), ('Rent Invoice', 'Rent Invoice'), ('NOC Certificate', 'NOC Certificate'), ('Insurance Document', 'Insurance Document'), ('Stamp Duty', 'Stamp Duty'), ('Notice', 'Notice'), ('Other', 'Other')], max_length=50),
        ),
    ]
