# Generated by Django 5.2.7 on 2026-07-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0006_alter_checkoutdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='documents_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
