# Generated by Django 5.2.7 on 2026-06-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('checkin_checkout', '0006_checkin_utility_adjustment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='agreement_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkin',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='agreement_template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='auto_reminder_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_agreement_generated', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='generated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='manager_signed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='renewal_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_agreement_signed', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='submitted_to_tenant_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='tenant_signed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkindocument',
            name='document_type',
            field=models.CharField(choices=[('Tenant ID Proof', 'Tenant ID Proof'), ('Passport Copy', 'Passport Copy'), ('Agreement Copy', 'Agreement Copy'), ('Inspection Photo', 'Inspection Photo'), ('Meter Reading Photo', 'Meter Reading Photo'), ('Company Seal', 'Company Seal')], max_length=50),
        ),
        migrations.CreateModel(
            name='CheckInPayment',
            fields=[
                ('check_in_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('receipt_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='checkin_checkout.checkin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_payments_created', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Check-In Payment',
                'verbose_name_plural': 'Check-In Payments',
                'db_table': 'check_in_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
