# Generated by Django 5.2.7 on 2026-06-21 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('checkin_checkout', '0007_checkin_agreement_notes_checkin_agreement_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='expected_handover_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='handover_completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='handover_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkin',
            name='key_booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_key_booked', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='key_booked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='key_notified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='key_prepared_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='tenant_confirmation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='checkindocument',
            name='document_type',
            field=models.CharField(choices=[('Tenant ID Proof', 'Tenant ID Proof'), ('Passport Copy', 'Passport Copy'), ('Agreement Copy', 'Agreement Copy'), ('Inspection Photo', 'Inspection Photo'), ('Meter Reading Photo', 'Meter Reading Photo'), ('Company Seal', 'Company Seal'), ('Key Handover Photo', 'Key Handover Photo'), ('Key Receipt', 'Key Receipt')], max_length=50),
        ),
        migrations.CreateModel(
            name='CheckInKey',
            fields=[
                ('check_in_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_number', models.CharField(max_length=100)),
                ('key_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Handovered', 'Handovered'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='checkin_checkout.checkin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_keys_created', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Check-In Key',
                'verbose_name_plural': 'Check-In Keys',
                'db_table': 'check_in_key',
                'ordering': ['check_in_key_id'],
            },
        ),
    ]
