# Generated by Django 5.2.7 on 2026-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0007_checkout_documents_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinkey',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Handed Over', 'Handed Over')], default='Pending', max_length=20),
        ),
    ]
