# Generated by Django 5.2.7 on 2026-06-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0008_checkin_expected_handover_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkindocument',
            name='linked_to_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkindocument',
            name='document_type',
            field=models.CharField(choices=[('Tenant ID Proof', 'Tenant ID Proof'), ('Passport Copy', 'Passport Copy'), ('Agreement Copy', 'Agreement Copy'), ('Inspection Photo', 'Inspection Photo'), ('Meter Reading Photo', 'Meter Reading Photo'), ('Company Seal', 'Company Seal'), ('Key Handover Photo', 'Key Handover Photo'), ('Key Receipt', 'Key Receipt'), ('Rent Invoice', 'Rent Invoice'), ('NOC Certificate', 'NOC Certificate'), ('Property Photo', 'Property Photo'), ('Move-In Checklist', 'Move-In Checklist'), ('Insurance Document', 'Insurance Document'), ('Stamp Duty', 'Stamp Duty'), ('Address Proof', 'Address Proof'), ('Police Clearance', 'Police Clearance'), ('Agreement Signed', 'Agreement Signed')], max_length=50),
        ),
    ]
