# Generated by Django 5.2.7 on 2026-06-22 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_department'),
        ('checkin_checkout', '0009_checkindocument_expiry_date_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInCheckOutManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='check_in_check_out_manager_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('team_size', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='check_in_check_out_manager_profiles/', verbose_name='Profile Picture')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.leadpermission')),
                ('property_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission')),
            ],
            options={
                'db_table': 'check_in_check_out_manager',
            },
        ),
        migrations.CreateModel(
            name='CheckInCheckOutEmployee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='check_in_check_out_employee_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.leadpermission')),
                ('property_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission')),
                ('manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='check_in_check_out_employee_manager_ref', to='checkin_checkout.checkincheckoutmanager')),
            ],
            options={
                'db_table': 'check_in_check_out_employee',
            },
        ),
    ]
