# Generated by Django 5.2.7 on 2026-06-22 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone_number'),
        ('checkin_checkout', '0010_checkincheckoutmanager_checkincheckoutemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='handed_over_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_key_handed_over', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='inspection_priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='key_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='repair_priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='tenant_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
