# Generated by Django 5.2.7 on 2026-06-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone_number'),
        ('checkin_checkout', '0012_remove_checkin_building_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutInspectionItem',
            fields=[
                ('check_out_inspection_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Walls & Ceilings', 'Walls & Ceilings'), ('Door & Windows', 'Door & Windows'), ('Electrical Fittings', 'Electrical Fittings'), ('Plumbing', 'Plumbing'), ('Kitchen', 'Kitchen'), ('Bathrooms', 'Bathrooms'), ('Furniture & Fixtures', 'Furniture & Fixtures'), ('Hall', 'Hall'), ('Others', 'Others')], max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('inspection_status', models.CharField(choices=[('Good', 'Good'), ('Issue', 'Issue'), ('Not Applicable', 'Not Applicable')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('repair_status', models.CharField(blank=True, choices=[('Required', 'Required'), ('Pending', 'Pending'), ('Repaired', 'Repaired')], max_length=20, null=True)),
                ('item_approval_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=20, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, max_length=500, null=True, upload_to='checkin_checkout/check_out_inspection_items/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_inspection_items_assigned', to='authentication.user')),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='checkin_checkout.checkout')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_inspection_items_created', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Check-Out Inspection Item',
                'verbose_name_plural': 'Check-Out Inspection Items',
                'db_table': 'check_out_inspection_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
