# Generated by Django 5.2.7 on 2026-06-30 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone_number'),
        ('checkin_checkout', '0013_add_check_out_inspection_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutUtilityReading',
            fields=[
                ('check_out_utility_reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('utility_type', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Gas', 'Gas'), ('Internet', 'Internet'), ('AC Service', 'AC Service'), ('Fuel', 'Fuel'), ('Solar', 'Solar'), ('Other Services', 'Other Services')], max_length=30)),
                ('meter_no', models.CharField(blank=True, max_length=50, null=True)),
                ('reading_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Fixed', 'Fixed'), ('Issues', 'Issues'), ('Not Applicable', 'Not Applicable')], default='Normal', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_readings', to='checkin_checkout.checkout')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_utility_readings_created', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Check-Out Utility Reading',
                'verbose_name_plural': 'Check-Out Utility Readings',
                'db_table': 'check_out_utility_reading',
                'ordering': ['-created_at'],
            },
        ),
    ]
