# Generated by Django 5.2.7 on 2026-06-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone_number'),
        ('checkin_checkout', '0014_add_check_out_utility_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutPayment',
            fields=[
                ('check_out_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('receipt_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='checkin_checkout.checkout')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_payments_created', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Check-Out Payment',
                'verbose_name_plural': 'Check-Out Payments',
                'db_table': 'check_out_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
