# Generated by Django 5.2.7 on 2026-06-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone_number'),
        ('checkin_checkout', '0015_add_check_out_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutKey',
            fields=[
                ('check_out_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_number', models.CharField(max_length=100)),
                ('key_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Returned', 'Returned'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='checkin_checkout.checkout')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_keys_created', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Check-Out Key',
                'verbose_name_plural': 'Check-Out Keys',
                'db_table': 'check_out_key',
                'ordering': ['check_out_key_id'],
            },
        ),
    ]
