# Generated by Django 5.2.7 on 2026-06-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0016_add_check_out_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='request_from',
            field=models.CharField(blank=True, choices=[('Tenant', 'Tenant'), ('Admin', 'Admin')], max_length=10, null=True),
        ),
    ]
