# Generated by Django 5.2.7 on 2026-07-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0017_add_checkout_request_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdocument',
            name='linked_to_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutinspectionitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='checkoutpayment',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdocument',
            name='document_type',
            field=models.CharField(choices=[('Tenant ID Proof', 'Tenant ID Proof'), ('Passport Copy', 'Passport Copy'), ('Agreement Copy', 'Agreement Copy'), ('Inspection Photo', 'Inspection Photo'), ('Meter Reading Photo', 'Meter Reading Photo'), ('Key Return Photo', 'Key Return Photo'), ('Notice', 'Notice'), ('Other', 'Other')], max_length=50),
        ),
    ]
