# Generated by Django 5.2.7 on 2026-07-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_checkout', '0018_add_cost_tax_doc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='finance_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkout',
            name='inspection_priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='key_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='key_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='repair_priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='settlement_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Settled', 'Settled'), ('Partially Settled', 'Partially Settled')], max_length=30, null=True),
        ),
    ]
