# Generated by Django 5.2.7 on 2025-11-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Country ID')),
                ('name', models.CharField(max_length=25, verbose_name='Country Name')),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
