# Generated by Django 5.2.7 on 2026-01-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTeamPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('agreement_team', models.BooleanField(default=False, verbose_name='Is Agreement Team Permitted')),
            ],
            options={
                'db_table': 'agreement_team_permission',
            },
        ),
        migrations.CreateModel(
            name='CollectionPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('collection', models.BooleanField(default=False, verbose_name='Is Collection Permitted')),
            ],
            options={
                'db_table': 'collection_permission',
            },
        ),
        migrations.CreateModel(
            name='FinancePermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('finance', models.BooleanField(default=False, verbose_name='Is Finance Permitted')),
            ],
            options={
                'db_table': 'finance_permission',
            },
        ),
        migrations.CreateModel(
            name='GenerateManagerPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('generate_manager', models.BooleanField(default=False, verbose_name='Is Generate Manager Permitted')),
            ],
            options={
                'db_table': 'generate_manager_permission',
            },
        ),
        migrations.CreateModel(
            name='HRPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('hr', models.BooleanField(default=False, verbose_name='Is HR Permitted')),
            ],
            options={
                'db_table': 'hr_permission',
            },
        ),
        migrations.CreateModel(
            name='ITPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('it', models.BooleanField(default=False, verbose_name='Is IT Permitted')),
            ],
            options={
                'db_table': 'it_permission',
            },
        ),
        migrations.CreateModel(
            name='LeadPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('lead', models.BooleanField(default=False, verbose_name='Is Lead Permitted')),
            ],
            options={
                'db_table': 'lead_permission',
            },
        ),
        migrations.CreateModel(
            name='LegalPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('legal', models.BooleanField(default=False, verbose_name='Is Legal Permitted')),
            ],
            options={
                'db_table': 'legal_permission',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('maintenance', models.BooleanField(default=False, verbose_name='Is Maintenance Permitted')),
            ],
            options={
                'db_table': 'maintenance_permission',
            },
        ),
        migrations.CreateModel(
            name='MarketingPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('marketing', models.BooleanField(default=False, verbose_name='Is Marketing Permitted')),
            ],
            options={
                'db_table': 'marketing_permission',
            },
        ),
        migrations.CreateModel(
            name='OwnerPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('owner', models.BooleanField(default=False, verbose_name='Is Owner Permitted')),
            ],
            options={
                'db_table': 'owner_permission',
            },
        ),
        migrations.CreateModel(
            name='PropertyPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('property', models.BooleanField(default=False, verbose_name='Is Property Permitted')),
            ],
            options={
                'db_table': 'property_permission',
            },
        ),
        migrations.CreateModel(
            name='ReceptionPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('reception', models.BooleanField(default=False, verbose_name='Is Reception Permitted')),
            ],
            options={
                'db_table': 'reception_permission',
            },
        ),
        migrations.CreateModel(
            name='StoreManagerPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('store_manager', models.BooleanField(default=False, verbose_name='Is Store Manager Permitted')),
            ],
            options={
                'db_table': 'store_manager_permission',
            },
        ),
        migrations.CreateModel(
            name='SupervisorPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('supervisor', models.BooleanField(default=False, verbose_name='Is Supervisor Permitted')),
            ],
            options={
                'db_table': 'supervisor_permission',
            },
        ),
    ]
