# Generated by Django 5.2.7 on 2025-12-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Permission Id')),
                ('property', models.BooleanField(default=False, verbose_name='Is Property Permitted')),
            ],
            options={
                'db_table': 'property_permission',
            },
        ),
    ]
