from rest_framework import serializers


class BuildingUserSerializer(serializers.Serializer):
    userId = serializers.IntegerField(read_only=True)
    name = serializers.CharField(read_only=True)


class BuildingGetSerializer(serializers.Serializer):
    buildingId = serializers.IntegerField(read_only=True)
    name = serializers.CharField(read_only=True)
    propertyType = serializers.CharField(read_only=True)
    block = serializers.CharField(read_only=True)
    totalFloors = serializers.IntegerField(read_only=True)
    yearOfConstruction = serializers.IntegerField(read_only=True)
    facilities = serializers.ListField(child=serializers.CharField(), read_only=True)
    rentalPurpose = serializers.CharField(read_only=True)
    allowedTenantTypes = serializers.ListField(child=serializers.CharField(), read_only=True)
    parking = serializers.BooleanField(read_only=True)
    lift = serializers.BooleanField(read_only=True)
    security = serializers.BooleanField(read_only=True)
    gasPipeline = serializers.BooleanField(read_only=True)
    waterSupply = serializers.BooleanField(read_only=True)
    intercom = serializers.BooleanField(read_only=True)
    fireSafety = serializers.BooleanField(read_only=True)
    projectName = serializers.CharField(read_only=True)
    privateGarden = serializers.BooleanField(read_only=True)
    privateParking = serializers.CharField(read_only=True)
    swimmingPool = serializers.CharField(read_only=True)
    terraceAccess = serializers.BooleanField(read_only=True)
    boundaryWall = serializers.BooleanField(read_only=True)
    driveway = serializers.BooleanField(read_only=True)
    waterSupply24x7 = serializers.BooleanField(read_only=True)
    securityGuard = serializers.BooleanField(read_only=True)
    clubhouseAccess = serializers.BooleanField(read_only=True)
    gym = serializers.BooleanField(read_only=True)
    childrensPlayArea = serializers.BooleanField(read_only=True)
    internalRoads = serializers.BooleanField(read_only=True)
    streetLights = serializers.BooleanField(read_only=True)
    gatedCommunity = serializers.BooleanField(read_only=True)
    powerBackup = serializers.BooleanField(read_only=True)
    commercialCategory = serializers.CharField(read_only=True)
    liftType = serializers.CharField(read_only=True)
    fireSafetyCompliant = serializers.BooleanField(read_only=True)
    emergencyExit = serializers.BooleanField(read_only=True)
    parkingAvailability = serializers.CharField(read_only=True)
    cctv = serializers.BooleanField(read_only=True)
    warehouseCategory = serializers.CharField(read_only=True)
    industrialEstateName = serializers.CharField(read_only=True)
    ownershipType = serializers.CharField(read_only=True)
    hasTransformer = serializers.BooleanField(read_only=True)
    waterSupplySource = serializers.CharField(read_only=True)
    hasDrainageSystem = serializers.BooleanField(read_only=True)
    hasInternetFiber = serializers.BooleanField(read_only=True)
    allowedIndustryTypes = serializers.ListField(child=serializers.CharField(), read_only=True)
    powerLoadKw = serializers.DecimalField(max_digits=8, decimal_places=2, read_only=True)
    hasDgBackup = serializers.BooleanField(read_only=True)
    addressLine1 = serializers.CharField(read_only=True)
    addressLine2 = serializers.CharField(read_only=True)
    areaZone = serializers.CharField(read_only=True)
    city = serializers.CharField(read_only=True)
    state = serializers.CharField(read_only=True)
    country = serializers.CharField(read_only=True)
    pincode = serializers.CharField(read_only=True)
    googleMapLocation = serializers.CharField(read_only=True)
    internalNotes = serializers.CharField(read_only=True)
    photos = serializers.ListField(child=serializers.URLField(), read_only=True)
    createdBy = BuildingUserSerializer(read_only=True)
    createdAt = serializers.DateTimeField(read_only=True)
    updatedAt = serializers.DateTimeField(read_only=True)
    isActive = serializers.BooleanField(read_only=True)


class BuildingResponseGetSerializer(serializers.Serializer):
    data = BuildingGetSerializer(read_only=True)
