# Generated by Django 5.2.7 on 2025-10-14 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='it_manager_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('projects_managed', models.IntegerField(default=0)),
                ('systems_overseen', models.IntegerField(default=0)),
                ('team_size', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'it_manager',
            },
        ),
        migrations.CreateModel(
            name='ITTechnician',
            fields=[
                ('technician_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='it_technician_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('skill_area', models.CharField(blank=True, max_length=100, null=True)),
                ('tickets_closed', models.IntegerField(default=0)),
                ('experience_years', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'it_technician',
            },
        ),
        migrations.CreateModel(
            name='ITEmployee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='it_employee_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role_title', models.CharField(blank=True, max_length=100, null=True)),
                ('tickets_resolved', models.IntegerField(default=0)),
                ('projects_assigned', models.IntegerField(default=0)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='IT.itmanager')),
            ],
            options={
                'db_table': 'it_employee',
            },
        ),
    ]
