# Generated by Django 5.2.7 on 2025-12-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ittechnician',
            old_name='experience_years',
            new_name='years_of_experience',
        ),
    ]
