# Generated by Django 5.2.7 on 2025-10-14 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tenant_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lease_start', models.DateField(blank=True, null=True)),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('property_name', models.CharField(blank=True, max_length=150, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tenant_manager_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('team_size', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tenant_manager',
            },
        ),
        migrations.CreateModel(
            name='TenantEmployee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tenant_employee_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='tenant.tenantmanager')),
            ],
            options={
                'db_table': 'tenant_employee',
            },
        ),
    ]
