# Generated by Django 5.2.7 on 2026-07-23 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_created', to='authentication.user')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketing.marketingcomment')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='authentication.user')),
            ],
            options={
                'db_table': 'marketing_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marketing_manager_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('campaigns_led', models.IntegerField(default=0)),
                ('team_size', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='marketing_manager_profiles/', verbose_name='Profile Picture')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.leadpermission')),
                ('property_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission')),
            ],
            options={
                'db_table': 'marketing_manager',
            },
        ),
        migrations.CreateModel(
            name='MarketingEmployee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marketing_employee_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('campaigns_assigned', models.IntegerField(default=0)),
                ('leads_generated', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.leadpermission')),
                ('property_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission')),
                ('manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marketing_employee_manager_ref', to='marketing.marketingmanager')),
            ],
            options={
                'db_table': 'marketing_employee',
            },
        ),
    ]
