# Generated by Django 5.2.7 on 2025-11-20 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPermission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead', models.BooleanField(default=False)),
                ('property', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'marketing_permission',
            },
        ),
        migrations.AlterField(
            model_name='marketingemployee',
            name='manager_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marketing_employee_manager_ref', to='marketing.marketingmanager'),
        ),
        migrations.AddField(
            model_name='marketingemployee',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marketing_employee_permission', to='marketing.marketingpermission'),
        ),
        migrations.AddField(
            model_name='marketingmanager',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marketing_manager_permission', to='marketing.marketingpermission'),
        ),
    ]
