# Generated by Django 5.2.7 on 2025-11-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpermission',
            name='lead',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingpermission',
            name='property',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
