# Generated by Django 5.2.7 on 2025-12-25 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_agreementteampermission_collectionpermission_and_more'),
        ('marketing', '0003_alter_marketingpermission_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingmanager',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='marketingemployee',
            name='permission',
        ),
        migrations.AddField(
            model_name='marketingemployee',
            name='lead_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.leadpermission'),
        ),
        migrations.AddField(
            model_name='marketingemployee',
            name='property_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission'),
        ),
        migrations.AddField(
            model_name='marketingmanager',
            name='lead_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.leadpermission'),
        ),
        migrations.AddField(
            model_name='marketingmanager',
            name='property_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission'),
        ),
        migrations.DeleteModel(
            name='MarketingPermission',
        ),
    ]
