# Generated by Django 5.2.7 on 2026-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_remove_marketingmanager_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmanager',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='marketing_manager_profiles/', verbose_name='Profile Picture'),
        ),
    ]
