# Generated by Django 5.2.7 on 2026-03-27 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('marketing', '0005_marketingmanager_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_created', to='authentication.user')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketing.marketingcomment')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='authentication.user')),
            ],
            options={
                'db_table': 'marketing_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
