# Generated by Django 5.2.7 on 2026-07-23 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reception_manager_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('team_size', models.IntegerField(default=0)),
                ('front_desk_count', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reception_manager',
            },
        ),
        migrations.CreateModel(
            name='ReceptionEmployee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reception_employee_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=100, null=True)),
                ('desk_number', models.CharField(blank=True, max_length=50, null=True)),
                ('calls_handled', models.IntegerField(default=0)),
                ('visitors_logged', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='reception.receptionmanager')),
            ],
            options={
                'db_table': 'reception_employee',
            },
        ),
    ]
