# Generated by Django 5.2.7 on 2026-01-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_access_token_user_refresh_token'),
        ('general_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalmanager',
            old_name='years_experience',
            new_name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='generalmanager',
            name='generalmanager_id',
        ),
        migrations.AddField(
            model_name='generalmanager',
            name='general_manager_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='general_manager_profile', serialize=False, to='authentication.user'),
            preserve_default=False,
        ),
    ]
