# Generated by Django 5.2.7 on 2026-07-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Country ID')),
                ('name', models.CharField(max_length=25, verbose_name='Country Name')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('nationality_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nationality Id')),
                ('name', models.CharField(max_length=25, verbose_name='Nationality Name')),
            ],
            options={
                'db_table': 'nationality',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='City Id')),
                ('name', models.CharField(max_length=25, verbose_name='Country Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_apis.country', verbose_name='Country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
