# Generated by Django 5.2.7 on 2026-07-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('hr_employee_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.user')),
            ],
        ),
    ]
