# Generated by Django 5.2.7 on 2025-12-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=25)),
                ('user_agent', models.TextField()),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=10)),
                ('model', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('end_point', models.CharField(max_length=125)),
                ('details', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user', verbose_name='User')),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=25)),
                ('user_agent', models.TextField()),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=10)),
                ('model', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('end_point', models.CharField(max_length=125)),
                ('details', models.JSONField()),
                ('created_on', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user', verbose_name='User')),
            ],
            options={
                'db_table': 'archive_log',
                'ordering': ['-created_on'],
            },
        ),
    ]
