# Generated by Django 5.2.7 on 2026-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='archivelog',
            name='ip_address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='archivelog',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
