# Generated by Django 5.2.7 on 2026-07-24 08:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_alter_activitylog_ip_address_alter_activitylog_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='archivelog',
            name='details',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
