# Generated by Django 5.2.7 on 2025-12-05 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTechnician',
            fields=[
                ('technician_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maintenance_technician_profile', serialize=False, to='authentication.user')),
                ('name', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('skill_type', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('assigned_jobs', models.IntegerField(default=0)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'maintenance_technician',
            },
        ),
        migrations.RenameField(
            model_name='maintenancemanager',
            old_name='years_experience',
            new_name='years_of_experience',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
