# Generated by Django 5.2.7 on 2026-01-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('maintenance', '0002_maintenancetechnician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceemployee',
            name='property_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission'),
        ),
        migrations.AddField(
            model_name='maintenancemanager',
            name='property_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission'),
        ),
        migrations.AddField(
            model_name='maintenancetechnician',
            name='property_permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.propertypermission'),
        ),
    ]
